# Generated by Django 3.1.1 on 2020-09-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmed',
            fields=[
                ('country', models.TextField(primary_key=True, serialize=False)),
                ('startdate', models.TextField(blank=True, db_column='startDate', null=True)),
                ('enddate', models.TextField(blank=True, db_column='endDate', null=True)),
                ('counts', models.TextField(blank=True, null=True)),
                ('total', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'confirmed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('country', models.TextField(primary_key=True, serialize=False)),
                ('startdate', models.TextField(blank=True, db_column='startDate', null=True)),
                ('enddate', models.TextField(blank=True, db_column='endDate', null=True)),
                ('counts', models.TextField(blank=True, null=True)),
                ('total', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'death',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('country', models.TextField(primary_key=True, serialize=False)),
                ('startdate', models.TextField(blank=True, db_column='startDate', null=True)),
                ('enddate', models.TextField(blank=True, db_column='endDate', null=True)),
                ('counts', models.TextField(blank=True, null=True)),
                ('total', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recovery',
                'managed': False,
            },
        ),
    ]
