# Generated by Django 3.1.1 on 2020-09-16 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrydata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryData',
        ),
    ]
