# Generated by Django 3.1.1 on 2020-09-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrydata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('country', models.TextField(db_column='Country', primary_key=True, serialize=False)),
                ('confirmed', models.TextField(blank=True, db_column='Confirmed', null=True)),
                ('startdate', models.TextField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.TextField(blank=True, db_column='EndDate', null=True)),
                ('currconfirmed', models.BigIntegerField(blank=True, db_column='CurrConfirmed', null=True)),
                ('death', models.TextField(blank=True, db_column='Death', null=True)),
                ('currdeath', models.BigIntegerField(blank=True, db_column='CurrDeath', null=True)),
                ('recovery', models.TextField(blank=True, db_column='Recovery', null=True)),
                ('currrecovery', models.BigIntegerField(blank=True, db_column='CurrRecovery', null=True)),
                ('active', models.TextField(blank=True, db_column='Active', null=True)),
                ('curractive', models.BigIntegerField(blank=True, db_column='CurrActive', null=True)),
                ('rank', models.IntegerField(blank=True, db_column='Rank', null=True)),
            ],
            options={
                'db_table': 'data',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Confirmed',
        ),
        migrations.DeleteModel(
            name='Death',
        ),
        migrations.DeleteModel(
            name='Recovery',
        ),
    ]
