# Generated by Django 3.1.1 on 2020-10-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrydata', '0002_auto_20200924_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(blank=True, null=True)),
                ('watchlist', models.TextField(blank=True, null=True)),
                ('top5', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscriber',
                'managed': False,
            },
        ),
    ]
