# Generated by Django 3.1.1 on 2020-09-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countrydata', '0002_delete_countrydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(blank=True, db_column='Country', null=True)),
                ('startdate', models.TextField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.TextField(blank=True, db_column='EndDate', null=True)),
                ('counts', models.TextField(blank=True, db_column='Counts', null=True)),
            ],
            options={
                'db_table': 'confirmed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(blank=True, db_column='Country', null=True)),
                ('startdate', models.TextField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.TextField(blank=True, db_column='EndDate', null=True)),
                ('counts', models.TextField(blank=True, db_column='Counts', null=True)),
            ],
            options={
                'db_table': 'death',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(blank=True, db_column='Country', null=True)),
                ('startdate', models.TextField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.TextField(blank=True, db_column='EndDate', null=True)),
                ('counts', models.TextField(blank=True, db_column='Counts', null=True)),
            ],
            options={
                'db_table': 'recovery',
                'managed': False,
            },
        ),
    ]
