# Generated by Django 3.1.1 on 2020-10-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrydata', '0003_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentdate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sentdate',
                'managed': False,
            },
        ),
    ]
