# Generated by Django 3.1.1 on 2020-10-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrydata', '0004_sentdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('msg', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
    ]
